[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"
add_imports = "from __future__ import annotations"

[tool.curlylint.rules]
image_alt = true
indent = true

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "django_project.settings"
